machine:
  services:
    - docker
database:
  override:
    - echo "Skip database phase"
dependencies:
  override:
    - echo "Skip dependencies phase"
deployment:
  master:
    branch: master
    commands:
      - git clone --branch ${MASTODON_GIT_BRANCH:-master} ${MASTODON_GIT_URL:-https://github.com/tootsuite/mastodon.git}
      - docker build --tag mastodon mastodon
      - docker run --env SECRET_KEY_BASE=dummy --volume $(pwd)/mastodon/public/assets:/mastodon/public/assets --volume $(pwd)/mastodon/public/packs:/mastodon/public/packs mastodon bundle exec rake assets:precompile
      - rm mastodon/.dockerignore
      - docker build --tag ${AWS_ECR_URL}:${CIRCLE_BUILD_NUM} mastodon
      - eval $(aws ecr get-login)
      - docker push ${AWS_ECR_URL}:${CIRCLE_BUILD_NUM}
test:
  override:
    - echo "Skip test phase"
