version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch-node-browsers
    working_directory: ~/repo
    environment:
      GRADLE_OPTS: -Xmx3g
      JVM_OPTS: -Xmx3g
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  test-java:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch-node-browsers
      steps:
      - run: ./gradlew test --no-daemon -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails" --max-workers 20
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/test-results/junit

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  test-yarn:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch-node-browsers
      steps:
      - run: yarn install
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
#deployment
      
  publish:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints: "SHA256:3NjaS3CruXShRtLGyu3cyF/Wp0zpmle2GlOz2NtoMRo"
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./gradlew -Pprod bootJar jibDockerBuild
      - run: docker tag junacards vinodplank/junacards:$CIRCLE_BUILD_NUM
      - run: docker push vinodplank/junacards:$CIRCLE_BUILD_NUM
      - run: ssh -o StrictHostKeyChecking=no ubuntu@13.235.249.241 "sed -i 's/juna-cards:[0-9][0-9]*/juna-cards:$CIRCLE_BUILD_NUM/g' ~/CircleCI/app.yml"
      - run: ssh -o StrictHostKeyChecking=no ubuntu@13.235.249.241 "/bin/bash ~/CircleCI/deploy.sh"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-java:
          requires:
            - build
      - test-yarn:
          requires:
            - build
      - publish:
          requires:
            - test-yarn
          filters:
            branches:
              only: master
